export const YAKAMOZ_IL = "İstanbul"

export const ISTANBUL_ILCELERI = [
  "Adalar",
  "Arnavutköy",
  "Ataşehir",
  "Avcılar",
  "Bağcılar",
  "Bahçelievler",
  "Bakırköy",
  "Başakşehir",
  "Bayrampaşa",
  "Beşiktaş",
  "Beykoz",
  "Beylikdüzü",
  "Beyoğlu",
  "Büyükçekmece",
  "Çatalca",
  "Çekmeköy",
  "Esenler",
  "Esenyurt",
  "Eyüpsultan",
  "Fatih",
  "Gaziosmanpaşa",
  "Güngören",
  "Kadıköy",
  "Kağıthane",
  "Kartal",
  "Küçükçekmece",
  "Maltepe",
  "Pendik",
  "Sancaktepe",
  "Sarıyer",
  "Silivri",
  "Sultanbeyli",
  "Sultangazi",
  "Şile",
  "Şişli",
  "Tuzla",
  "Ümraniye",
  "Üsküdar",
  "Zeytinburnu",
] as const

export const MAHALLELER_BY_ILCE: Record<string, string[]> = {
  Avcılar: [
    "Merkez",
    "Ambarlı",
    "Cihangir",
    "Denizköşkler",
    "Firuzköy",
    "Gümüşpala",
    "Tahtakale",
    "Üniversite",
  ],
  Beylikdüzü: [
    "Adnan Kahveci",
    "Barış",
    "Büyükşehir",
    "Cumhuriyet",
    "Dereağzı",
    "Gürpınar",
    "Kavaklı",
    "Yakuplu",
  ],
  Esenyurt: [
    "Akçaburgaz",
    "Bağlarçeşme",
    "Cumhuriyet",
    "Fatih",
    "Güzelyurt",
    "İnönü",
    "Namık Kemal",
    "Pınar",
    "Yenikent",
  ],
  Başakşehir: [
    "Altınşehir",
    "Bahçeşehir",
    "Başak",
    "Başakşehir",
    "Güvercintepe",
    "Kayabaşı",
    "Şahintepe",
  ],
}

export function getMahalleSuggestions(ilce: string): string[] {
  return MAHALLELER_BY_ILCE[ilce] ?? []
}
